#ifndef QDRIVE_VERSION_H
#define QDRIVE_VERSION_H

#define QDRIVE_VERSION_STRING "0.9.2-1"
#define QDRIVE_VERSION_MAJOR 0
#define QDRIVE_VERSION_MINOR 9
#define QDRIVE_VERSION_RELEASE 2
#define QDRIVE_VERSION_PACKAGE 1
#define QDRIVE_VVERSION_STRING "v0.9.2-1"

#endif // QDRIVE_VERSION_H
