/* This file was automatically generated by makeVer v0.4.0-2 */
/* Result from git describe --dirty --always: 0.9.1-1-dirty */

#ifndef QDRIVE_VERSION_H
#define QDRIVE_VERSION_H

#include <QString>

#define QDRIVE_VERSION_DIRTY 
#define QDRIVE_VERSION_MAJOR 0
#define QDRIVE_VERSION_RELEASE 1
#define QDRIVE_VERSION_PACKAGE 1
#define QDRIVE_VVERSION_STRING "v0.9.1-1-dirty"
#define QDRIVE_VERSION_ADDITIONAL_COMMITS -1
#define QDRIVE_VERSION_MINOR 9
#define QDRIVE_VERSION_STRING "0.9.1-1-dirty"

namespace QDrive
{
	namespace Version
	{
		int major();
		int minor();
		int release();
		int package();
		
		int additionalCommits();
		bool isDirty();
		QString string();
		QString vString();
		
	};
};

#endif // QDRIVE_VERSION_H
