/* This file was automatically generated by makeVer v0.6.0 */
/* Result from git describe --dirty --always: 0.9.1-1-5-g53223b6-dirty */

#ifndef QDRIVE_VERSION_H
#define QDRIVE_VERSION_H

#define QDRIVE_VERSION_MINOR 9
#define QDRIVE_VERSION_SHA "53223b6"
#define QDRIVE_VERSION_MAJOR 0
#define QDRIVE_VERSION_ADDITIONAL_COMMITS 5
#define QDRIVE_VERSION_PACKAGE 1
#define QDRIVE_VERSION_STRING "0.9.1-1-5-g53223b6-dirty"
#define QDRIVE_VERSION_MAJMINREL_OR_SHA "53223b6"
#define QDRIVE_VERSION_DIRTY 
#define QDRIVE_VERSION_RELEASE 1
#define QDRIVE_VVERSION_STRING "v0.9.1-1-5-g53223b6-dirty"

#endif // QDRIVE_VERSION_H
