/* This file was automatically generated by makeVer v0.4.0-2 */
/* Result from git describe --dirty --always: 0.9.1-1-dirty */

#include "Version.h"

int QDrive::Version::major()
{
	return 0;
}

int QDrive::Version::minor()
{
	return 9;
}

int QDrive::Version::release()
{
	return 1;
}

int QDrive::Version::package()
{
	return 1;
}



int QDrive::Version::additionalCommits()
{
	return -1;
}

bool QDrive::Version::isDirty()
{
	return true;
}

QString QDrive::Version::string()
{
	return "0.9.1-1-dirty";
}

QString QDrive::Version::vString()
{
	return "v0.9.1-1-dirty";
}


